plugins:
  - jekyll-remote-theme
remote_theme: samarsault/plainwhite-jekyll

plainwhite:
  name: Jan Škoruba
  tagline: Developer
  date_format: "%b %-d, %Y"
  sitemap: true
  dark_mode: true
  social_links:
    github: skoruba
